services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: migrate_test
      POSTGRES_USER: migrate_user
      POSTGRES_PASSWORD: migrate_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U migrate_user -d migrate_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: